name: JollyKite
options:
  bundleIdPrefix: com.jollykite
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: "XM6SL4JUGF"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  JollyKiteShared:
    path: ./JollyKiteShared

targets:
  JollyKite:
    type: application
    platform: iOS
    sources:
      - path: JollyKite
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jollykite.app
        INFOPLIST_FILE: JollyKite/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: JollyKite/JollyKite.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"
    dependencies:
      - package: JollyKiteShared
      - target: JollyKiteWidgets
        embed: true
    entitlements:
      path: JollyKite/JollyKite.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.jollykite.shared

  JollyKiteWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: JollyKiteWidgets
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jollykite.app.widgets
        INFOPLIST_FILE: JollyKiteWidgets/Info.plist
        CODE_SIGN_ENTITLEMENTS: JollyKiteWidgets/JollyKiteWidgets.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - package: JollyKiteShared
    entitlements:
      path: JollyKiteWidgets/JollyKiteWidgets.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.jollykite.shared

  JollyKiteMac:
    type: application
    platform: macOS
    sources:
      - path: JollyKiteMacApp
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jollykite.mac
        INFOPLIST_FILE: JollyKiteMacApp/Info.plist
        CODE_SIGN_ENTITLEMENTS: JollyKiteMacApp/JollyKiteMacApp.entitlements
    dependencies:
      - package: JollyKiteShared
      - target: JollyKiteMacWidgets
        embed: true
    entitlements:
      path: JollyKiteMacApp/JollyKiteMacApp.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
        com.apple.security.application-groups:
          - group.com.jollykite.shared

  JollyKiteMacWidgets:
    type: app-extension
    platform: macOS
    sources:
      - path: JollyKiteMacWidgets
        excludes:
          - "**/.DS_Store"
      - path: JollyKiteWidgets
        excludes:
          - "**/.DS_Store"
          - JollyKiteWidgets.swift
          - Views/WindCircularView.swift
          - Views/WindRectangularView.swift
          - Views/WindInlineView.swift
          - Info.plist
          - JollyKiteWidgets.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jollykite.mac.widgets
        INFOPLIST_FILE: JollyKiteMacWidgets/Info.plist
        CODE_SIGN_ENTITLEMENTS: JollyKiteMacWidgets/JollyKiteMacWidgets.entitlements
    dependencies:
      - package: JollyKiteShared
    entitlements:
      path: JollyKiteMacWidgets/JollyKiteMacWidgets.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
        com.apple.security.application-groups:
          - group.com.jollykite.shared
