name: JollyKite
options:
  bundleIdPrefix: com.jollykite
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  JollyKiteShared:
    path: ./JollyKiteShared

targets:
  JollyKite:
    type: application
    platform: iOS
    sources:
      - path: JollyKite
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jollykite.app
        INFOPLIST_FILE: JollyKite/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: JollyKite/JollyKite.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"
    dependencies:
      - package: JollyKiteShared
      - target: JollyKiteWidgets
        embed: true
    entitlements:
      path: JollyKite/JollyKite.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.jollykite.shared

  JollyKiteWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: JollyKiteWidgets
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jollykite.app.widgets
        INFOPLIST_FILE: JollyKiteWidgets/Info.plist
        CODE_SIGN_ENTITLEMENTS: JollyKiteWidgets/JollyKiteWidgets.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - package: JollyKiteShared
    entitlements:
      path: JollyKiteWidgets/JollyKiteWidgets.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.jollykite.shared
